import { Karla } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Whatsapp from "@/components/whatsapp/Whatsapp";

const karla = Karla({ subsets: ["latin"] });

export const metadata = {
  title: "new export web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={karla.className}>
        <Navbar />
        {children}
        <Whatsapp />
      </body>
    </html>
  );
}
